version: '3.4'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: surveydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_host=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8080:80
  
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    expose:
      - 9000
  
  ui:
    build: ./ui
    container_name: ui
    restart: always
    expose:
      - 80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:80"
    